trainingInput:
  scaleTier: CUSTOM
  masterType: complex_model_l_gpu
#  masterType: standard_gpu
#  workerCount: 8
#  workerType: standard_gpu
#  parameterServerCount: 3
#  parameterServerType: standard
